# Github action to build Raspberry Pi image from main branch

name: Build image

on:
  workflow_dispatch:

jobs:
  build_main_image:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch latest release tag
        run: |
          LATEST_RELEASE="$(curl -sL https://api.github.com/repos/buanet/ioBroker.raspberry-os/releases/latest | jq -r '.tag_name')"
          echo "Latest release tag: $LATEST_RELEASE"
          echo "RELEASE_TAG=$LATEST_RELEASE" >> $GITHUB_ENV

      - name: Checkout ioBroker.raspberry-os latest stable
        uses: actions/checkout@v4
        with:
          repository: 'buanet/ioBroker.raspberry-os'
          ref: ${{ env.RELEASE_TAG }}
          path: ioBroker.raspberry-os

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Prepare build
        run: |
          echo 'Install prerequisites'
          sudo apt-get update
          sudo apt-get install binfmt-support
          echo 'Lock build date...'
          DATE=$(date '+%Y-%m-%d')
          echo "Build date: $DATE"
          echo "DATE=$DATE" >> $GITHUB_ENV
          echo 'Done.'
          echo ''
          echo 'Clone pi-gen build tool...'
          git clone https://github.com/RPi-Distro/pi-gen
          echo 'Done.'
          echo ''
          echo 'Prepare config file and iobroker stage...'
          cp ./ioBroker.raspberry-os/config ./pi-gen/config
          cp -R ./ioBroker.raspberry-os/stage-iobroker ./pi-gen/stage-iobroker
          chmod -R +x pi-gen
          echo 'Done.'
          echo ''
          echo 'Change work dir...'
          cd ./pi-gen
          echo 'Done.'
          echo ''
          echo 'Add skip files for unused stages...'
          touch ./stage3/SKIP ./stage4/SKIP ./stage5/SKIP
          touch ./stage4/SKIP_IMAGES ./stage5/SKIP_IMAGES
          rm ./stage4/EXPORT* ./stage5/EXPORT*
          echo 'Done.'
          echo ''
          echo 'Manipulate build script...'
          sed -i 's/-e "GIT_HASH=${GIT_HASH}"/-e "GIT_HASH=${GIT_HASH}" --hostname iobroker-pi/' ./build-docker.sh
          ## temp fix for issues with debian bullseye
          sed -i 's/:bullseye/:buster/' ./build-docker.sh
          sed -i 's/:bullseye/:buster/' ./Dockerfile
          ## temp fix for missing gpg command
          # sed -i 's/fdisk/fdisk gnupg2/' ./Dockerfile
          echo 'Done.'
          echo ''

      - name: Build image
        timeout-minutes: 90
        run: |
          cd ./pi-gen
          ./build-docker.sh

      - name: Get publishing info
        run: |
          IMAGE_PATH=$(find ./pi-gen/deploy/ -name '*.zip')
          echo "Image path: $IMAGE_PATH"
          echo "IMAGE_PATH=$IMAGE_PATH" >> $GITHUB_ENV
          IMAGE_NAME=$(echo $IMAGE_PATH | cut -d'/' -f4-)
          echo "Image name: $IMAGE_NAME"
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV

      - name: Prepare deploy for upload
        run: |
          echo 'Generate deploy.zip...'
          cd ./pi-gen/deploy && zip -r ../../deploy.zip ./* 
          echo 'Done.'
          echo ''

      - name: Publish image to Github release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_name: buanet/ioBroker.raspberry-os
          repo_token: ${{ secrets.ACTIONS_PAT }}
          tag: ${{ env.RELEASE_TAG }}
          file: ${{ env.IMAGE_PATH }}
          asset_name: ${{ env.DATE }}_RaspberryOS_ioBroker_Image_${{ env.RELEASE_TAG }}.zip
          overwrite: true

#      - name: Upload deploy.zip to cloud.buanet.de
#        run: |
#          echo 'Uploading...'
#          curl -u ${{ secrets.NC_USER }}:${{ secrets.NC_PASS }} -T ./deploy.zip "https://${{ secrets.NC_HOST }}/remote.php/dav/files/fileshare/rpios-iobroker/${{ env.DATE }}_Deploy_RaspberryOS_ioBroker_${{ env.RELEASE_TAG }}.zip"
#          echo 'Done.'
#          echo ''

      - name: Trigger update rpi-imager
        uses: benc-uk/workflow-dispatch@v1.2
        with:
          workflow: Update rpi-imager repo
          repo: buanet/ioBroker.raspberry-os
          token: ${{ secrets.ACTIONS_PAT }}

  retry_when_failed:
    name: Retry workflow when failed
    runs-on: ubuntu-latest
    if: failure()
    needs: [build_main_image]
    steps:
      - name: Trigger build
        uses: benc-uk/workflow-dispatch@v1.2
        with:
          workflow: Build image
          repo: buanet/ioBroker.raspberry-os
          token: ${{ secrets.ACTIONS_PAT }}
